#!/bin/bash

# Firefly III Updater v1.0.3
# 05.11.2024 Patrick Raddatz
# This shell script will update your Firefly III installation to the latest version.

echo "This is the Firefly III Updater v1.0.3 …"
echo

# Fetch the latest release from the GitHub API
latest_version=$(curl -sI https://github.com/firefly-iii/firefly-iii/releases/latest | awk -F '/' '/^location/ {print  substr($NF, 1, length($NF)-1)}')

# Print current version and the latest version available on GitHub
echo "Latest Firefly III version is:      $latest_version"
file="/var/www/virtual/$USER/firefly_iii/changelog.md"
current_version=$(grep -m 1 -oP '## \K.*?(?= -)' "$file")
echo "The currently installed version is: $current_version"
read -p "Would you like to update? (y/n): " choice

if [[ $choice == "y" || $choice == "Y" ]]; then
    echo "Proceeding …"
elif [[ $choice == "n" || $choice == "N" ]]; then
    echo "Quitting …"
    exit
else
    echo "Invalid choice. Please choose 'y' to proceed or 'n' to quit."
fi

# Remove the backup of the prior version we have created before
cd /var/www/virtual/"$USER"/ || exit
rm -rf firefly-iii-old 
echo "Backup folder has been removed."

# Download and upack the latest version from GitHub
wget https://github.com/firefly-iii/firefly-iii/releases/download/"${latest_version}"/FireflyIII-"${latest_version}".zip  2>&1
echo "New Firefly III version $latest_version has been downloaded."
mkdir firefly-iii-updated
echo "New Firefly III folder has been created."
unzip -q FireflyIII-v*.zip -d firefly-iii-updated
echo "Firefly III version $latest_version has been unpacked."
rm FireflyIII-v*.zip 
echo "Firefly III zip file has been removed."

# Copy environment and htaccess files over to the new Firefly version
cp firefly_iii/.env firefly-iii-updated/.env
cp firefly_iii/public/.htaccess firefly-iii-updated/public/.htaccess
echo "Environment and htaccess files have been copied."

# Copy storage files over to the new Firefly version
cp firefly_iii/storage/upload/* firefly-iii-updated/storage/upload/ || true
cp firefly_iii/storage/export/* firefly-iii-updated/storage/export/ || true
echo "Storage files have been copied."

# Clear the cache
cd firefly-iii-updated || exit
rm -rf bootstrap/cache/*
echo "Cache has been cleared."

# Do PHP stuff
php artisan firefly-iii:upgrade-database 2>&1
php artisan firefly-iii:correct-database 2>&1
php artisan firefly-iii:report-integrity 2>&1
php artisan firefly-iii:laravel-passport-keys 2>&1
echo "PHP stuff has been done."

# Rename old and new base folders accordingly and exit nicely
cd .. 
mv firefly_iii firefly-iii-old 
mv firefly-iii-updated firefly_iii
echo "Old and new base folders have been renamed."
echo "Firefly III has now been updated to version $latest_version."
echo "Goodbye :)"

exit
